config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'blogs#index'

  #user #blog
   resources :users do 
      resources :blogs, except: %i[index]
   end
  
  #comment
    post '/blog/:blog_id/comment/create' => 'comments#create', as: 'create_comment'
    delete '/blog/:blog_id/comment/:comment_id/delete' => 'comments#delete', as: 'delete_comment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum:2, maximum:50}
  validates :content_text, presence: true, length: {minimum:2, maximum:1000}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  validates :commenter, presence: true, length: {minimum:2, maximum:30}
  validates :comment_text, presence: true, length: {minimum:2, maximum:300}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs , dependent: :destroy
  validates :firstname, presence: true, length: {minimum:2, maximum:15}
  validates :lastname, presence: true, length: {minimum:2, maximum:15}
  validates :username, presence: true, length: {minimum:2, maximum:15}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def find_blog
    @user = User.find(current_user.id)
    @blog = Blog.find(params[:id])
  end

  def find_user
    @user = User.find(current_user.id)
  end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :firstname, :lastname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  

  def index
    @blogs = Blog.all
  end

  def new
    @user = User.find(params[:user_id])
    @blog  = @user.blogs.build()
  end

  def create
    @user = User.find(params[:user_id])
    @blog = @user.blogs.build(blog_params)
    if @blog.save 
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @blog = Blog.find(params[:id])
    @comments = @blog.comments
  end

  def edit
    find_blog
  end

  def update
    find_blog
    if @blog.update(blog_params)
      redirect_to user_blog_path(@user,@blog)
    else
      render 'edit'
    end
  end

  def destroy
    find_blog
    @blog.destroy
    redirect_to user_path(@user)
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content_text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @blog = @user.blogs.find(params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    redirect_to show_blog_path(user_id: @user.id, blog_id: @blog.id)
  end

  def delete
    @comment = Comment.find(params[:comment_id])   
    @blog = @comment.blog
    @comment.destroy
    redirect_to show_blog_path(user_id: @blog.user.id, blog_id: @blog.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :comment_text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @blogs = @user.blogs
  end

  def edit
    
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    # byebug
    @user.destroy
    sign_out_and_redirect(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :firstname, :lastname ,:password)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.erb
<h1> Edit blog </h1>

<%= render 'layouts/username', user: @user%>

<%= form_with model: @blog, url: user_blog_path(@user, @blog), local: true do |f| %>
 <%= render 'devise/shared/error_general', resource: @blog %>
  <div>
    <strong>Title: </strong>
    <%= f.text_field :title %>
  </div>
  <br>
   <div>
    <strong>Content: </strong>
    <%= f.text_area :content_text %>
  </div>
  <br>
  <%= f.submit%>
<% end %>

<p>
  <%= link_to  "Back", user_blog_path(@user, @blog) %>
  <%= link_to  "List of Blogs", user_path(@user)%>
</p>

app/views/blogs/index.erb
<h1>List of all blogs</h1>
<%= render 'devise/shared/logged_in_as', user: current_user %>

<p> 
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete%> |
  <%= link_to  "List of Users", users_path %> |
  <%= link_to  "Write new blog", new_user_blog_path(user_id: current_user.id) %>
</p>


<% if @blogs.empty? %>
  <span> No blogs yet. </span>
<% else %>
  <table>
      <tr>
        <th>Writter</th>
        <th>Title</th>
        <th>Blog</th>
      </tr>
    <% @blogs.map do |blog|%>
      <tr>
        <td><%= link_to  blog.user.username, users_path(blog.user) %></td>
        <td><strong><%= blog.title%></strong></td>
        <td><%= blog.content_text%></td>
        <td><%= link_to  "Show", user_blog_path(blog.user, blog) %></td>
          <% if blog.user == current_user %>
            <td><%= link_to  "Edit", edit_user_blog_path(blog.user, blog) %></td>
            <td><%= link_to  "Delete", user_blog_path(blog.user, blog), method: :delete %></td>
          <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/blogs/new.erb
<h1> Write new blog </h1>

<%= form_with model: @blog, url: user_blogs_path(@user), local: true do |f| %>
  <%= render 'devise/shared/error_general', resource: @blog %>
  <div>
    <strong>Title: </strong>
    <%= f.text_field :title %>
  </div>
  <br>
   <div>
    <strong>Content: </strong>
    <%= f.text_area :content_text %>
  </div>
  <br>
  <%= f.submit%>
<% end %>

<%= link_to  "Back", user_path(@user) %>

app/views/blogs/show.erb
<h1>Show Blog</h1>

<%= render 'layouts/username', user: @user %>

<p>
  <% if current_user == @user %>
     <%= link_to  "Edit", edit_user_blog_path(@user, @blog) %> | 
     <%= link_to  "Delete", user_blog_path(@user, @blog), method: :delete, data: { confirm: 'Are you sure?' }%> | 
  <% end %>
  <%= link_to  "Blogs of writter", user_path(@user)%> |
  <%= link_to  "All Blogs", root_path() %>
</p>
<div>
  <strong>Title: </strong>
  <%= @blog.title%>
</div>
  <br>
<div>
  <strong>Text: </strong>
  <%= @blog.content_text %>
</div>

<h2> Comments: </h2>
  <table>
    <% if @comments.empty? %>
        <p>No comments.</p>
    <%else%>
      <% @comments.map do |comment|%>
      <tr>
        <td><strong><%= comment.commenter%>: </strong></td>
        <td><%= comment.comment_text%></td>
        <td><%= link_to  "delete", delete_comment_path(blog_id: @blog, comment_id: comment.id), method: :delete %></td>
      </tr>
      <% end %>
    <% end %>
  </table>
  <br>
  <br>


<%= form_with model: @blog.comments.build(), url: create_comment_path(user_id: @user.id, blog_id: @blog.id), local: true do |f| %>  
  <div>
    <strong>Commenter: </strong>
    <%= f.text_field :commenter %>
  </div>
  <br>
   <div>
    <strong>Comment: </strong>
    <%= f.text_area :comment_text %>
  </div>
  <br>
  <%= f.submit%>
<% end %>

app/views/layouts/_username.erb
<h3>
  <span>writter:</span>
  <span><%= link_to  user.username, user_path(user) %></span>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogMg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/index.erb
<h1>All Users</h1>
<%= render 'devise/shared/logged_in_as', user: current_user %>
<p>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete%> |
  <%= link_to  "All Blogs", index_blog_path(user_id: current_user) %> |
  <%= link_to  "Write new blog", new_blog_path(user_id: current_user.id) %>
</p>

<table>
  <tr>
    <td>Firstname: </td>
    <td><%= current_user.firstname %></td>
  </tr>
   <tr>
    <td>Lastname: </td>
    <td><%= current_user.lastname %></td>
  </tr>
   <tr>
    <td>Username: </td>
    <td><%= current_user.username %></td>
  </tr>
   <tr>
    <td>email: </td>
    <td><%= current_user.email %></td>
  </tr>
</table>
<td><%= link_to  "Blogs", user_path(current_user) %></td>
<td><%= link_to  "Edit", edit_user_path(current_user) %></td>
<td><%= link_to  "Delete", user_path(current_user), method: :delete %></td>
<br>
<br>
<br>
<table>
List of Users:
    <tr>
      <th>Firstname</th>
      <th>lastname</th>
      <th>username</th>
    </tr>
    
    <% if @users.count == 1 %>
      <td> No other users. </td>
    <% else %>
      <% @users.map do |user|%>
        <% if user != current_user %>
          <tr>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
            <td><%= user.username %></td>
            <td><%= link_to  "Blogs", user_path(user) %></td>
          </tr>
        <% end %>
      <% end %> 
    <% end %>
</table>

app/views/users/edit.erb
<h1>Edit User</h1>

<%= link_to  "Back", user_index_path %> |
<%= link_to  "Show", user_path(@user) %>
<%= form_with model: @user, url: user_path , local: true do |f| %>
   <%= render "devise/shared/error_messages", resource: @user %>
  <table>
    <tr>
      <td><strong> Firstname: </strong></td>
      <td><%= f.text_field :firstname %></td>
    </tr>
     <tr>
      <td><strong> Lastname: </strong></td>
      <td><%= f.text_field :lastname %></td>
    </tr>
     <tr>
      <td><strong> Username: </strong></td>
      <td><%= f.text_field :username %></td>
    </tr>
    <tr>
      <td><strong> Email: </strong></td>
      <td><%= f.email_field :email %></td>
    </tr>
    <tr>
      <td><strong> Password: </strong></td>
      <td><%= f.password_field :password %></td>
    </tr>
  </table>
  <%= f.submit %>
<% end %>

app/views/users/index.erb
<h1>All Users</h1>
<%= render 'devise/shared/logged_in_as', user: current_user %>
<p>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete%> |
  <%= link_to  "All Blogs", root_path() %> |
  <%= link_to  "Write new blog", new_user_blog_path(user_id: current_user.id) %>
</p>

<table>
  <tr>
    <td>Firstname: </td>
    <td><%= current_user.firstname %></td>
  </tr>
   <tr>
    <td>Lastname: </td>
    <td><%= current_user.lastname %></td>
  </tr>
   <tr>
    <td>Username: </td>
    <td><%= current_user.username %></td>
  </tr>
   <tr>
    <td>email: </td>
    <td><%= current_user.email %></td>
  </tr>
</table>
<td><%= link_to  "Blogs", user_path(current_user) %></td>
<td><%= link_to  "Edit", edit_user_path(current_user) %></td>
<td><%= link_to  "Delete", user_path(current_user), method: :delete %></td>
<br>
<br>
<br>
<table>
List of Users:
    <tr>
      <th>Firstname</th>
      <th>lastname</th>
      <th>username</th>
    </tr>
    
    <% if @users.count == 1 %>
      <td> No other users. </td>
    <% else %>
      <% @users.map do |user|%>
        <% if user != current_user %>
          <tr>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
            <td><%= user.username %></td>
            <td><%= link_to  "Blogs", user_path(user) %></td>
          </tr>
        <% end %>
      <% end %> 
    <% end %>
</table>

app/views/users/new.erb
<h1>Create New User</h1>

<%= form_with model: @user, url: create_user_path , local: true do |f| %>
  <table>
    <tr>
      <td><strong> Firstname: </strong></td>
      <td><%= f.text_field :firstname %></td>
    </tr>
    <tr>
      <td><strong> Lastname: </strong></td>
      <td><%= f.text_field :lastname %></td>
    </tr>
    <tr>
      <td><strong> Username: </strong></td>
      <td><%= f.text_field :username %></td>
    </tr>
    <tr>
      <td><strong> Password: </strong></td>
      <td><%= f.password_field :password %></td>
    </tr>
  </table>
  <%= f.submit %>
<% end %>

app/views/users/show.erb
<%= render 'devise/shared/logged_in_as', user: current_user %>
<%= render 'layouts/username', user: @user%>
<p>
  <%= link_to  "list of users", users_path %> |
  <%= link_to  "All Blogs", root_path() %>
</p>

<h2> Blogs: </h2>


<% if current_user == @user %>
  <p><%= link_to  "Write new blog", new_user_blog_path(user_id: current_user.id) %></p>
<% end %>


<% if @user.blogs.empty? %>
  <span> No blogs yet. </span>
<% else %>
  <table>
    <% @blogs.map do |blog|%>
      <tr>
        <td><strong><%= blog.title%></strong></td>
        <td><%= blog.content_text%></td>
        <td><%= link_to  "Show", user_blog_path(blog.user, blog) %></td>
          <% if blog.user == current_user %>
            <td><%= link_to  "Edit", edit_user_blog_path(blog.user, blog) %></td>
            <td><%= link_to  "Delete", user_blog_path(blog.user, blog), method: :delete %></td>
          <% end %>
      </tr>
    <% end %>
  </table>
<% end %>